# Generated by Django 5.1.5 on 2025-01-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
                ("first_name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "idcliente",
                    models.AutoField(
                        db_column="idCliente", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.TextField()),
                ("apellido", models.TextField()),
                ("dni", models.IntegerField(unique=True)),
                ("numtel", models.IntegerField(db_column="numTel")),
            ],
            options={
                "db_table": "Cliente",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Conexion",
            fields=[
                (
                    "idconexion",
                    models.AutoField(
                        db_column="idConexion", primary_key=True, serialize=False
                    ),
                ),
                ("fechaalta", models.IntegerField(db_column="fechaAlta")),
                ("numero", models.IntegerField(unique=True)),
                ("idcliente", models.IntegerField(db_column="idCliente", unique=True)),
                (
                    "idservicio",
                    models.IntegerField(db_column="idServicio", unique=True),
                ),
                (
                    "iddireccion",
                    models.IntegerField(db_column="idDireccion", unique=True),
                ),
            ],
            options={
                "db_table": "Conexion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
                ("action_time", models.DateTimeField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "iddomicilio",
                    models.AutoField(
                        db_column="idDomicilio", primary_key=True, serialize=False
                    ),
                ),
                ("calle", models.TextField()),
                ("departamento", models.TextField(blank=True, null=True)),
                ("numero", models.IntegerField()),
                ("piso", models.IntegerField(blank=True, null=True)),
                ("idlocalidad", models.IntegerField(db_column="idLocalidad")),
            ],
            options={
                "db_table": "Domicilio",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "idlocalidad",
                    models.AutoField(
                        db_column="idLocalidad", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.TextField()),
            ],
            options={
                "db_table": "Localidad",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Operacion",
            fields=[
                (
                    "idoperacion",
                    models.AutoField(
                        db_column="idOperacion", primary_key=True, serialize=False
                    ),
                ),
                ("fechahora", models.IntegerField(db_column="fechaHora")),
                ("motivo", models.TextField()),
                ("numero", models.IntegerField(unique=True)),
                ("idpersona", models.IntegerField(db_column="idPersona")),
                ("idconexion", models.IntegerField(db_column="idConexion")),
            ],
            options={
                "db_table": "Operacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "idpersona",
                    models.AutoField(
                        db_column="idPersona", primary_key=True, serialize=False
                    ),
                ),
                ("apellido", models.TextField()),
                ("nombre", models.TextField()),
                ("dni", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "Persona",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "idservicio",
                    models.AutoField(
                        db_column="idServicio", primary_key=True, serialize=False
                    ),
                ),
                ("cantidadmegas", models.IntegerField(db_column="cantidadMegas")),
                ("precio", models.FloatField()),
            ],
            options={
                "db_table": "Servicio",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "idvisita",
                    models.AutoField(
                        db_column="idVisita", primary_key=True, serialize=False
                    ),
                ),
                ("estado", models.IntegerField()),
                ("fechahora", models.IntegerField(db_column="fechaHora")),
                ("observacion", models.TextField()),
                ("idpersona", models.IntegerField(db_column="idPersona")),
                ("idconecxion", models.IntegerField(db_column="idConecxion")),
            ],
            options={
                "db_table": "Visita",
                "managed": False,
            },
        ),
    ]
