# Generated by Django 5.1.5 on 2025-01-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Operacion",
        ),
        migrations.DeleteModel(
            name="Persona",
        ),
        migrations.DeleteModel(
            name="Visita",
        ),
    ]
