# Generated by Django 5.1.5 on 2025-01-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_delete_operacion_delete_persona_delete_visita"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conexion",
            options={},
        ),
    ]
