# Generated by Django 5.1.5 on 2025-01-28 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_conexion_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conexion",
            name="iddireccion",
        ),
        migrations.AddField(
            model_name="conexion",
            name="iddomicilio",
            field=models.ForeignKey(
                db_column="idDomicilio",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.domicilio",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conexion",
            name="fechaalta",
            field=models.DateField(db_column="fechaAlta"),
        ),
        migrations.AlterField(
            model_name="conexion",
            name="idcliente",
            field=models.ForeignKey(
                db_column="idCliente",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="conexion",
            name="idservicio",
            field=models.ForeignKey(
                db_column="idServicio",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.servicio",
            ),
        ),
    ]
