# Generated by Django 5.1.5 on 2025-01-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_conexion_iddireccion_conexion_iddomicilio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={},
        ),
        migrations.AlterModelOptions(
            name="domicilio",
            options={},
        ),
        migrations.AlterModelOptions(
            name="localidad",
            options={},
        ),
        migrations.AlterModelOptions(
            name="servicio",
            options={},
        ),
    ]
