# Generated by Django 5.1.5 on 2025-01-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_cliente_options_alter_domicilio_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domicilio",
            name="idlocalidad",
            field=models.ForeignKey(
                db_column="idLocalidad",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.localidad",
            ),
        ),
    ]
